packages:
    - "client"
    - "server"

catalog:
    "@eslint/compat": "^1.3.2"
    "@eslint/js": "^9.34.0"
    "@sveltejs/adapter-auto": "^6.1.0"
    "@sveltejs/kit": "^2.36.2"
    "@sveltejs/vite-plugin-svelte": "^6.1.3"
    "@tailwindcss/forms": "^0.5.10"
    "@tailwindcss/typography": "^0.5.16"
    "@tailwindcss/vite": "^4.1.12"
    "@types/node": "^24.2.0"
    "daisyui": "^5.0.50"
    "eslint": "^9.34.0"
    "eslint-config-prettier": "^10.1.8"
    "eslint-plugin-svelte": "^3.11.0"
    "globals": "^16.3.0"
    "less": "^4.4.1"
    "prettier": "^3.6.2"
    "prettier-plugin-multiline-arrays": "^4.0.3"
    "prettier-plugin-svelte": "^3.4.0"
    "prettier-plugin-tailwindcss": "^0.6.14"
    "svelte": "^5.38.3"
    "svelte-check": "^4.3.1"
    "tailwindcss": "^4.1.12"
    "tsup": "^8.5.0"
    "tsx": "^4.20.5"
    "typescript": "^5.9.2"
    "typescript-eslint": "^8.40.0"
    "unplugin-auto-import": "^20.0.0"
    "vite": "^7.1.3"
